//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bkav.eGovCloud.SmsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.ISMSServiceSoap")]
    public interface ISMSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSServiceSoap/SendSms", ReplyAction="http://tempuri.org/ISMSServiceSoap/SendSmsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="phoneNumberErrors")]
        string[] SendSms(string[] toPhoneNumbers, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSServiceSoap/Send", ReplyAction="http://tempuri.org/ISMSServiceSoap/SendResponse")]
        void Send(string message, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSServiceSoap/SendWithPriorityByType", ReplyAction="http://tempuri.org/ISMSServiceSoap/SendWithPriorityByTypeResponse")]
        void SendWithPriorityByType(int type, string message, string phoneNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSServiceSoapChannel : Bkav.eGovCloud.SmsServiceReference.ISMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<Bkav.eGovCloud.SmsServiceReference.ISMSServiceSoap>, Bkav.eGovCloud.SmsServiceReference.ISMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] SendSms(string[] toPhoneNumbers, string message) {
            return base.Channel.SendSms(toPhoneNumbers, message);
        }
        
        public void Send(string message, string phoneNumber) {
            base.Channel.Send(message, phoneNumber);
        }
        
        public void SendWithPriorityByType(int type, string message, string phoneNumber) {
            base.Channel.SendWithPriorityByType(type, message, phoneNumber);
        }
    }
}
