//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bkav.eGovCloud.Business.DVCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="DVCService.DVCServiceHoSoSoap")]
    public interface DVCServiceHoSoSoap {
        
        // CODEGEN: Generating message contract since element name madonvi from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/CapNhatTinhHinhGiaiQuyetHoSoCapHuyen" +
            "", ReplyAction="*")]
        Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse CapNhatTinhHinhGiaiQuyetHoSoCapHuyen(Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapNhatTinhHinhGiaiQuyetHoSoCapHuyen", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody Body;
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest() {
        }
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest(Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string madonvi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string maxacthuc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string linhvuc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string thang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sohstiepnhan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sohsdaxuly;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sohsdunghan;
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody() {
        }
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody(string madonvi, string maxacthuc, string linhvuc, string nam, string thang, string sohstiepnhan, string sohsdaxuly, string sohsdunghan) {
            this.madonvi = madonvi;
            this.maxacthuc = maxacthuc;
            this.linhvuc = linhvuc;
            this.nam = nam;
            this.thang = thang;
            this.sohstiepnhan = sohstiepnhan;
            this.sohsdaxuly = sohsdaxuly;
            this.sohsdunghan = sohsdunghan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponseBody Body;
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse() {
        }
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse(Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResult;
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponseBody() {
        }
        
        public CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponseBody(string CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResult) {
            this.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResult = CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DVCServiceHoSoSoapChannel : Bkav.eGovCloud.Business.DVCService.DVCServiceHoSoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DVCServiceHoSoSoapClient : System.ServiceModel.ClientBase<Bkav.eGovCloud.Business.DVCService.DVCServiceHoSoSoap>, Bkav.eGovCloud.Business.DVCService.DVCServiceHoSoSoap {
        
        public DVCServiceHoSoSoapClient() {
        }
        
        public DVCServiceHoSoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DVCServiceHoSoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DVCServiceHoSoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DVCServiceHoSoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse Bkav.eGovCloud.Business.DVCService.DVCServiceHoSoSoap.CapNhatTinhHinhGiaiQuyetHoSoCapHuyen(Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest request) {
            return base.Channel.CapNhatTinhHinhGiaiQuyetHoSoCapHuyen(request);
        }
        
        public string CapNhatTinhHinhGiaiQuyetHoSoCapHuyen(string madonvi, string maxacthuc, string linhvuc, string nam, string thang, string sohstiepnhan, string sohsdaxuly, string sohsdunghan) {
            Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest inValue = new Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequest();
            inValue.Body = new Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenRequestBody();
            inValue.Body.madonvi = madonvi;
            inValue.Body.maxacthuc = maxacthuc;
            inValue.Body.linhvuc = linhvuc;
            inValue.Body.nam = nam;
            inValue.Body.thang = thang;
            inValue.Body.sohstiepnhan = sohstiepnhan;
            inValue.Body.sohsdaxuly = sohsdaxuly;
            inValue.Body.sohsdunghan = sohsdunghan;
            Bkav.eGovCloud.Business.DVCService.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResponse retVal = ((Bkav.eGovCloud.Business.DVCService.DVCServiceHoSoSoap)(this)).CapNhatTinhHinhGiaiQuyetHoSoCapHuyen(inValue);
            return retVal.Body.CapNhatTinhHinhGiaiQuyetHoSoCapHuyenResult;
        }
    }
}
