INSERT INTO `permission`(`PermissionKey`, `PermissionName`, `ModuleName`, `Description`) VALUES ('DocumentRelatedIndex', 'Danh sách DocumentRelated', 'Quản lý văn bản liên quan', 'Cho phép người dùng xem danh sách văn bản liên quan');
INSERT INTO `permission`(`PermissionKey`, `PermissionName`, `ModuleName`, `Description`) VALUES ('DocumentRelatedCreate', 'Thêm mới DocumentRelated', 'Quản lý văn bản liên quan', 'Cho phép người dùng thêm mới văn bản liên quan');
INSERT INTO `permission`(`PermissionKey`, `PermissionName`, `ModuleName`, `Description`) VALUES ('DocumentRelatedEdit', 'Chỉnh sửa DocumentRelated', 'Quản lý văn bản liên quan', 'Cho phép người dùng chỉnh sửa văn bản liên quan');
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelated.NotExist", "Văn bản liên quan không tồn tại!.");
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelated.Deleted.Error", "Lỗi khi xóa văn bản liên quan.");
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelatedName.Exist", "Tên văn bản liên quan đã tồn tại.");
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelated.Created", "Thêm mới thành công!");
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelated.ConfirmDelete", "Bạn có chắc muốn xóa văn bản liên quan này không?!.");
INSERT INTO `resource` VALUES(NULL, "Customer.DocumentRelated.NotPermission", "Bạn không có quyền truy cập vào xem thông tin các văn bản liên quan!.");
INSERT INTO `resource` VALUES(NULL, "Customer.DocumentRelated.NotPermissionEdit", "Bạn không có quyền chỉnh sửa văn bản liên quan!.");
INSERT INTO `resource` VALUES(NULL, "Customer.DocumentRelated.NotPermissionCreate", "Bạn không có quyền tạo mới văn bản liên quan!.");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Numbers", "STT");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Name", "Tiêu đề");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Edit", "Sửa");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Delete", "Xóa");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Edit.Button", "Sửa");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.Column.Delete.Button", "Xóa");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.Index.List.NullValue", "Không có văn bản liên quan nào");
INSERT INTO `resource` VALUES(NULL, "egov.resources.sitemap.DocumentRelated", "Văn bản liên quan");
INSERT INTO `resource` VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.DocumentRelated.Index.Search.Fields.DocumentRelatedName.Label", "Bộ lọc");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.CreateOrEdit.Fields.Name.Required", "Bạn phải nhập tên văn bản liên quan!");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.CreateOrEdit.Fields.Name.MaxLength", "Tên văn bản liên quan không được vượt quá 500 ký tự!");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.CreateOrEdit.Fields.File.Required", "Bạn chưa tải file lên!");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.CreateOrEdit.Fields.File.Label", "File");
INSERT INTO `resource` VALUES(NULL, "DocumentRelated.CreateOrEdit.Fields.Name.Label", "Tiêu đề");