insert into resource VALUES(NULL, "Customer.ReportMode.NotPermission","Bạn không có quyển vào danh sách chế độ báo cáo!");
insert into resource VALUES(NULL, "Customer.ReportMode.NotPermissionCreate","Bạn không có quyển thêm mới chế độ báo cáo!");
insert into resource VALUES(NULL, "Customer.ReportMode.NotPermissionEdit","Bạn không có quyển chỉnh sửa chế độ báo cáo!");
insert into resource VALUES(NULL, "Customer.ReportMode.NotPermissionDelete","Bạn không có quyển xóa chế độ báo cáo!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.ReportMode.NotExist","Chế độ báo cáo không tồn tại!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.ReportMode.ConfirmDelete","Bạn chắc chắn muốn xóa chế độ báo cáo này chứ?");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Code.Label","Mã chế độ báo cáo");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Name.Label","Tên chế độ báo cáo");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Subject.Label","Nội dung yêu cầu báo cáo");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.IssueOrg.Label","Cơ quan ban hành");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.IssueDate.Label","Ngày phát hành");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Number.Label","Số văn bản");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Notation.Label","Ký hiệu văn bản");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.RefNotation.Label","Số ký hiệu văn bản");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.ReportMode.Label","Loại chế độ báo cáo");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.File.Label","Files");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Code.Required","Bạn phải nhập mã chế độ báo cáo!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.Name.Required","Bạn phải nhập tên chế độ báo cáo!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.IssueOrg.Required","Bạn phải nhập Cơ quan ban hành chế độ báo cáo!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.RefNotation.Required","Bạn chưa nhập số ký hiệu vắn bản!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.RefNotation.Exist","số ký hiệu vắn bản đã tồn tại!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.RefNotation.QuestionYesNo","Bạn chắc chắn muốn xóa số ký hiệu vắn bản này chứ?");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.File.QuestionYesNo","Bạn chắc chắn muốn xóa tập tin này chứ?");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.ReportMode.Created","Thêm mới chế độ báo cáo thành công!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.ReportMode.Updated","Chỉnh sửa chế độ báo cáo thành công!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.ReportMode.Deleted","Xóa chế độ báo cáo thành công!");
insert into resource VALUES(NULL, "ReportMode.CreateOrEdit.Fields.IssueDate.NotValid","Ngày phát hành không hợp lệ. Định dạng ngày dd/MM/yyyy!");