insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogName.Label","Tên danh mục:");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.ParentId.Label","Danh mục cha:");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogCode.Label","Mã danh mục:");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogName.Required","Bạn phải nhập tên danh mục!");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogName.MaxLength","Tên danh mục không được vượt quá 500 ký tự!");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogCode.Required","Bạn phải nhập mã danh mục!");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.InCatalogId.Required","Bạn phải nhập danh mục!");
insert into resource VALUES(NULL, "IndicatorCatalogValue.CreateOrEdit.Fields.IndicatorCatalogCode.MaxLength","Mã danh mục không được vượt quá 300 ký tự!");
insert into resource VALUES(NULL, "Customer.IndicatorCatalogValue.NotPermission","Bạn không có quyển vào xem danh sách chỉ tiêu!");
insert into resource VALUES(NULL, "Customer.IndicatorCatalogValue.NotPermissionCreate","Bạn không có quyển thêm mới chỉ tiêu!");
insert into resource VALUES(NULL, "Customer.IndicatorCatalogValue.NotPermissionUpdate","Bạn không có quyển chỉnh sửa chỉ tiêu!");
insert into resource VALUES(NULL, "Customer.IndicatorCatalogValue.NotPermissionDelete","Bạn không có quyển xóa chỉ tiêu!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.IndicatorCatalogValue.Updated","Cập nhật chỉ tiêu thành công!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.IndicatorCatalogValue.Deleted","Xóa chỉ tiêu thành công!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.IndicatorCatalogValue.Created","Thêm mới chỉ tiêu thành công!");
insert into resource VALUES(NULL, "Bkav.eGovCloud.Areas.Admin.IndicatorCatalogValue.ConfirmDelete","Bạn chắc chắn muốn xóa chỉ tiêu này chứ?");
INSERT INTO `permission` VALUES ('0', 'IndicatorCatalogValueIndex',	'Danh sách chỉ tiêu','Quản lý chỉ tiêu',	'Cho phép người dùng xem danh sách chỉ tiêu');
INSERT INTO `permission` VALUES ('0', 'IndicatorCatalogValueCreate',	'Thêm mới chỉ tiêu','Quản lý chỉ tiêu',	'Cho phép người dùng thêm mới chỉ tiêu');
INSERT INTO `permission` VALUES ('0', 'IndicatorCatalogValueEdit',	'Chỉnh sửa chỉ tiêu','Quản lý chỉ tiêu',	'Cho phép người dùng chỉnh sửa chỉ tiêu');
INSERT INTO `permission` VALUES ('0', 'IndicatorCatalogValueDelete',	'Xóa chỉ tiêu','Quản lý chỉ tiêu',	'Cho phép người dùng xóa chỉ tiêu');