//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bkav.eGovCloud.eGovLicense {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessageBase", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bkav.eGovCloud.eGovLicense.CheckLisenseRequestMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bkav.eGovCloud.eGovLicense.RegisterRequestMessage))]
    public partial class RequestMessageBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseCode {
            get {
                return this.LicenseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseCodeField, value) != true)) {
                    this.LicenseCodeField = value;
                    this.RaisePropertyChanged("LicenseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicKeyField, value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckLisenseRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    public partial class CheckLisenseRequestMessage : Bkav.eGovCloud.eGovLicense.RequestMessageBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentNumberOfUsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentNumberOfUsers {
            get {
                return this.CurrentNumberOfUsersField;
            }
            set {
                if ((this.CurrentNumberOfUsersField.Equals(value) != true)) {
                    this.CurrentNumberOfUsersField = value;
                    this.RaisePropertyChanged("CurrentNumberOfUsers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterRequestMessage", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    public partial class RegisterRequestMessage : Bkav.eGovCloud.eGovLicense.RequestMessageBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessageBase", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bkav.eGovCloud.eGovLicense.CheckLisenceResponseMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bkav.eGovCloud.eGovLicense.RegisterResponseMessage))]
    public partial class ResponseMessageBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckLisenceResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    public partial class CheckLisenceResponseMessage : Bkav.eGovCloud.eGovLicense.ResponseMessageBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateExpriredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateExprired {
            get {
                return this.DateExpriredField;
            }
            set {
                if ((this.DateExpriredField.Equals(value) != true)) {
                    this.DateExpriredField = value;
                    this.RaisePropertyChanged("DateExprired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfUsers {
            get {
                return this.NumberOfUsersField;
            }
            set {
                if ((this.NumberOfUsersField.Equals(value) != true)) {
                    this.NumberOfUsersField = value;
                    this.RaisePropertyChanged("NumberOfUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Bkav.eGovLicense.Service.Message")]
    [System.SerializableAttribute()]
    public partial class RegisterResponseMessage : Bkav.eGovCloud.eGovLicense.ResponseMessageBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateExpriredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfUsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateExprired {
            get {
                return this.DateExpriredField;
            }
            set {
                if ((this.DateExpriredField.Equals(value) != true)) {
                    this.DateExpriredField = value;
                    this.RaisePropertyChanged("DateExprired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfUsers {
            get {
                return this.NumberOfUsersField;
            }
            set {
                if ((this.NumberOfUsersField.Equals(value) != true)) {
                    this.NumberOfUsersField = value;
                    this.RaisePropertyChanged("NumberOfUsers");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="eGovLicense.ILicense")]
    public interface ILicense {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicense/Register", ReplyAction="http://tempuri.org/ILicense/RegisterResponse")]
        Bkav.eGovCloud.eGovLicense.RegisterResponseMessage Register(Bkav.eGovCloud.eGovLicense.RegisterRequestMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicense/CheckLicense", ReplyAction="http://tempuri.org/ILicense/CheckLicenseResponse")]
        Bkav.eGovCloud.eGovLicense.CheckLisenceResponseMessage CheckLicense(Bkav.eGovCloud.eGovLicense.CheckLisenseRequestMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicenseChannel : Bkav.eGovCloud.eGovLicense.ILicense, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenseClient : System.ServiceModel.ClientBase<Bkav.eGovCloud.eGovLicense.ILicense>, Bkav.eGovCloud.eGovLicense.ILicense {
        
        public LicenseClient() {
        }
        
        public LicenseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bkav.eGovCloud.eGovLicense.RegisterResponseMessage Register(Bkav.eGovCloud.eGovLicense.RegisterRequestMessage message) {
            return base.Channel.Register(message);
        }
        
        public Bkav.eGovCloud.eGovLicense.CheckLisenceResponseMessage CheckLicense(Bkav.eGovCloud.eGovLicense.CheckLisenseRequestMessage message) {
            return base.Channel.CheckLicense(message);
        }
    }
}
