//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bkav.eGovCloud.Business.PublishInvoice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublishInvoice.PublishServiceSoap")]
    public interface PublishServiceSoap {
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvResponse ImportAndPublishInv(Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.ImportInvResponse ImportInv(Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequest request);
        
        // CODEGEN: Generating message contract since element name invIDs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.publishInvResponse publishInv(Bkav.eGovCloud.Business.PublishInvoice.publishInvRequest request);
        
        // CODEGEN: Generating message contract since element name XMLCusData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.UpdateCusResponse UpdateCus(Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequest request);
        
        // CODEGEN: Generating message contract since element name certSerial from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.setCusCertResponse setCusCert(Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequest request);
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHashInvWithToken", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenResponse getHashInvWithToken(Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvWithToken", ReplyAction="*")]
        Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenResponse publishInvWithToken(Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInv", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequestBody Body;
        
        public ImportAndPublishInvRequest() {
        }
        
        public ImportAndPublishInvRequest(Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int convert;
        
        public ImportAndPublishInvRequestBody() {
        }
        
        public ImportAndPublishInvRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvResponseBody Body;
        
        public ImportAndPublishInvResponse() {
        }
        
        public ImportAndPublishInvResponse(Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportAndPublishInvResult;
        
        public ImportAndPublishInvResponseBody() {
        }
        
        public ImportAndPublishInvResponseBody(string ImportAndPublishInvResult) {
            this.ImportAndPublishInvResult = ImportAndPublishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInv", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequestBody Body;
        
        public ImportInvRequest() {
        }
        
        public ImportInvRequest(Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        public ImportInvRequestBody() {
        }
        
        public ImportInvRequestBody(string xmlInvData, string username, string password, int convert) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.ImportInvResponseBody Body;
        
        public ImportInvResponse() {
        }
        
        public ImportInvResponse(Bkav.eGovCloud.Business.PublishInvoice.ImportInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvResult;
        
        public ImportInvResponseBody() {
        }
        
        public ImportInvResponseBody(string ImportInvResult) {
            this.ImportInvResult = ImportInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInv", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.publishInvRequestBody Body;
        
        public publishInvRequest() {
        }
        
        public publishInvRequest(Bkav.eGovCloud.Business.PublishInvoice.publishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.ArrayOfInt invIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvRequestBody() {
        }
        
        public publishInvRequestBody(Bkav.eGovCloud.Business.PublishInvoice.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            this.invIDs = invIDs;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.publishInvResponseBody Body;
        
        public publishInvResponse() {
        }
        
        public publishInvResponse(Bkav.eGovCloud.Business.PublishInvoice.publishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvResult;
        
        public publishInvResponseBody() {
        }
        
        public publishInvResponseBody(string publishInvResult) {
            this.publishInvResult = publishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCus", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequestBody Body;
        
        public UpdateCusRequest() {
        }
        
        public UpdateCusRequest(Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLCusData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> convert;
        
        public UpdateCusRequestBody() {
        }
        
        public UpdateCusRequestBody(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            this.XMLCusData = XMLCusData;
            this.username = username;
            this.pass = pass;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.UpdateCusResponseBody Body;
        
        public UpdateCusResponse() {
        }
        
        public UpdateCusResponse(Bkav.eGovCloud.Business.PublishInvoice.UpdateCusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCusResult;
        
        public UpdateCusResponseBody() {
        }
        
        public UpdateCusResponseBody(int UpdateCusResult) {
            this.UpdateCusResult = UpdateCusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCert", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequestBody Body;
        
        public setCusCertRequest() {
        }
        
        public setCusCertRequest(Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string certSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string certString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public setCusCertRequestBody() {
        }
        
        public setCusCertRequestBody(string certSerial, string certString, string cusCode, string username, string pass) {
            this.certSerial = certSerial;
            this.certString = certString;
            this.cusCode = cusCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.setCusCertResponseBody Body;
        
        public setCusCertResponse() {
        }
        
        public setCusCertResponse(Bkav.eGovCloud.Business.PublishInvoice.setCusCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setCusCertResult;
        
        public setCusCertResponseBody() {
        }
        
        public setCusCertResponseBody(int setCusCertResult) {
            this.setCusCertResult = setCusCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHashInvWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHashInvWithToken", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequestBody Body;
        
        public getHashInvWithTokenRequest() {
        }
        
        public getHashInvWithTokenRequest(Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHashInvWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string serialCert;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string invToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int convert;
        
        public getHashInvWithTokenRequestBody() {
        }
        
        public getHashInvWithTokenRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string serialCert, int type, string invToken, string pattern, string serial, int convert) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.serialCert = serialCert;
            this.type = type;
            this.invToken = invToken;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHashInvWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHashInvWithTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenResponseBody Body;
        
        public getHashInvWithTokenResponse() {
        }
        
        public getHashInvWithTokenResponse(Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHashInvWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHashInvWithTokenResult;
        
        public getHashInvWithTokenResponseBody() {
        }
        
        public getHashInvWithTokenResponseBody(string getHashInvWithTokenResult) {
            this.getHashInvWithTokenResult = getHashInvWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvWithToken", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequestBody Body;
        
        public publishInvWithTokenRequest() {
        }
        
        public publishInvWithTokenRequest(Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public publishInvWithTokenRequestBody() {
        }
        
        public publishInvWithTokenRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvWithTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenResponseBody Body;
        
        public publishInvWithTokenResponse() {
        }
        
        public publishInvWithTokenResponse(Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvWithTokenResult;
        
        public publishInvWithTokenResponseBody() {
        }
        
        public publishInvWithTokenResponseBody(string publishInvWithTokenResult) {
            this.publishInvWithTokenResult = publishInvWithTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublishServiceSoapChannel : Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap>, Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap {
        
        public PublishServiceSoapClient() {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.ImportAndPublishInv(Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequest request) {
            return base.Channel.ImportAndPublishInv(request);
        }
        
        public string ImportAndPublishInv(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            Bkav.eGovCloud.Business.PublishInvoice.ImportAndPublishInvResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).ImportAndPublishInv(inValue);
            return retVal.Body.ImportAndPublishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.ImportInvResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.ImportInv(Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequest request) {
            return base.Channel.ImportInv(request);
        }
        
        public string ImportInv(string xmlInvData, string username, string password, int convert) {
            Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            Bkav.eGovCloud.Business.PublishInvoice.ImportInvResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).ImportInv(inValue);
            return retVal.Body.ImportInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.publishInvResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.publishInv(Bkav.eGovCloud.Business.PublishInvoice.publishInvRequest request) {
            return base.Channel.publishInv(request);
        }
        
        public string publishInv(Bkav.eGovCloud.Business.PublishInvoice.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            Bkav.eGovCloud.Business.PublishInvoice.publishInvRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.publishInvRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            Bkav.eGovCloud.Business.PublishInvoice.publishInvResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).publishInv(inValue);
            return retVal.Body.publishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.UpdateCusResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.UpdateCus(Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequest request) {
            return base.Channel.UpdateCus(request);
        }
        
        public int UpdateCus(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            Bkav.eGovCloud.Business.PublishInvoice.UpdateCusResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).UpdateCus(inValue);
            return retVal.Body.UpdateCusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.setCusCertResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.setCusCert(Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequest request) {
            return base.Channel.setCusCert(request);
        }
        
        public int setCusCert(string certSerial, string certString, string cusCode, string username, string pass) {
            Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            Bkav.eGovCloud.Business.PublishInvoice.setCusCertResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).setCusCert(inValue);
            return retVal.Body.setCusCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.getHashInvWithToken(Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequest request) {
            return base.Channel.getHashInvWithToken(request);
        }
        
        public string getHashInvWithToken(string Account, string ACpass, string xmlInvData, string username, string password, string serialCert, int type, string invToken, string pattern, string serial, int convert) {
            Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.serialCert = serialCert;
            inValue.Body.type = type;
            inValue.Body.invToken = invToken;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            Bkav.eGovCloud.Business.PublishInvoice.getHashInvWithTokenResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).getHashInvWithToken(inValue);
            return retVal.Body.getHashInvWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenResponse Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap.publishInvWithToken(Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequest request) {
            return base.Channel.publishInvWithToken(request);
        }
        
        public string publishInvWithToken(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial) {
            Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequest inValue = new Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequest();
            inValue.Body = new Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            Bkav.eGovCloud.Business.PublishInvoice.publishInvWithTokenResponse retVal = ((Bkav.eGovCloud.Business.PublishInvoice.PublishServiceSoap)(this)).publishInvWithToken(inValue);
            return retVal.Body.publishInvWithTokenResult;
        }
    }
}
